// import App from '@system.app'
//
// @Component
// struct NavigationBar {
//
//   @State title : string = ''
//   @State isLeftHind : boolean = false
//   @State isRightHind : boolean = false
//   @State backImage : string = 'app.media.icon_back'
//
//   build() {
//
//     Row(){
//
//       Image($r(this.backImage)).width(32).height(32).margin({left:8,top:6,bottom:6})
//       Text(this.title).width(222).height(22).fontSize($r('app.float.size_16'))
//
//     }.width('100%').height(60).backgroundColor($r('app.color.color_cb'))
//
//   }
//
// }